# fly.toml app configuration file generated for cineclub-backend-nodejs on 2023-09-21T17:49:47-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cineclub-backend-nodejs"
primary_region = "eze"

[mounts]
  source="assets"
  destination="/assets"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
